; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif32
board = nodemcu-32s
framework = arduino
build_src_filter = +<*> -<dockingstation/>
monitor_speed = 115200
upload_speed = 921600
debug_tool = jlink
; https://docs.platformio.org/en/latest/plus/debug-tools/jlink.html
; https://gojimmypi.blogspot.com/2017/05/vscode-jtag-debugging-of-esp32-part-1.html
; JTAG interface
; upload_protocol = jlink-jtag
;targets = upload, monitor

;[env:nodemcuv2_upstream_develop]
;platform = https://github.com/platformio/platform-espressif32.git
;board = nodemcu-32s
;framework = arduino
;monitor_speed = 115200
;upload_speed = 921600
;debug_tool = jlink

;[env:esp32thing]
;platform = espressif32
;board = esp32thing
;framework = arduino
;monitor_speed = 115200
;upload_speed = 921600
;targets = upload, monitor

; OTA flashing
;upload_port = <mower IP-address>
;upload_flags = --auth=<OTA password>

lib_deps =
  ArduinoLog=https://github.com/thijse/Arduino-Log.git
  SparkFun Ublox Arduino Library=https://github.com/sparkfun/SparkFun_Ublox_Arduino_Library.git#v1.7.2
  SparkFun LSM9DS1 IMU @ 2.0.0
  Adafruit ADS1X15=https://github.com/soligen2010/Adafruit_ADS1X15.git#7d67b451f739e9a63f40f2d6d139ab582258572b
  ArduinoJson=https://github.com/bblanchon/ArduinoJson.git#v5.13.5
  blemasle/MCP23017 @ 2.0.0
  jgromes/RadioLib
  sandeepmistry/LoRa
  gioblu/PJON
  Nanopb
